---------------------------------------------------------------

Задание 2
try {
   int d = 0;
   double catchedRes1 = intArray[8] / d;
   System.out.println("catchedRes1 = " + catchedRes1);
} catch (ArithmeticException e) {
   System.out.println("Catching exception: " + e);
}

Комментарии к задачи 2:
1. данные исключения относятся к UNCHECKED, т.е. данные исключения можно обработать через IF
2. в задание 2 прослеживается два возможных исключения:
    2.1 ArithmeticException
    2.2 IndexOutOfВoundsException
    В задачи два отсутстует исключение IndexOutOfВoundsException, необходимо добавить CATCH


---------------------------------------------------------------

Задание 3

public static void main(String[] args) throws Exception {
   try {
       int a = 90;
       int b = 3;
       System.out.println(a / b);
       printSum(23, 234);
       int[] abc = { 1, 2 };
       abc[3] = 9;
   } catch (Throwable ex) {
       System.out.println("Что-то пошло не так...");
   } catch (NullPointerException ex) {
       System.out.println("Указатель не может указывать на null!");
   } catch (IndexOutOfBoundsException ex) {
       System.out.println("Массив выходит за пределы своего размера!");
   }
}
public static void printSum(Integer a, Integer b) throws FileNotFoundException {
   System.out.println(a + b);
}

Комментарии к задачи 3:

1. Throwable является классом всех исключений. Любые подклассы после класса Throwable работать не будут.
В Intellij IDEA будет ошибка.
2. В методе printSum выброс - "throws FileNotFoundException" лишний. Связь с файлом отсуствут.
3. Исключение NullPointerException ex - так же является лишним в данной программе.
